[project]
name = "bus-sign"
revision = "1.0"

[providers]
local = "dotenv://.env"
openbao = "openbao://secrets.scottylabs.org/secret"
openbao-ci = "openbao://secrets.scottylabs.org/secret?auth=jwt&role=ci&audience=openbao"

[profiles.default]
AWS_ACCESS_KEY_ID = { description = "sccache S3 access key ID", ref = { item = "shared/sccache", field = "AWS_ACCESS_KEY_ID" } }
AWS_SECRET_ACCESS_KEY = { description = "sccache S3 secret access key", ref = { item = "shared/sccache", field = "AWS_SECRET_ACCESS_KEY" } }
CACHIX_AUTH_TOKEN = { description = "Cachix auth token", ref = { item = "shared/cachix", field = "CACHIX_AUTH_TOKEN" } }
PRT_API_KEY = { description = "Pittsburgh Regional Transit API key" }
OPENWEATHER_API_KEY = { description = "OpenWeatherMap API key" }

[profiles.prod]

[profiles.preview]

[profiles.staging]

[profiles.dev.defaults]
providers = ["openbao"]

[profiles.dev]
PRT_API_KEY = { providers = ["local"] }
OPENWEATHER_API_KEY = { providers = ["local"] }

[profiles.ci.defaults]
required = false
providers = ["openbao-ci"]

[profiles.ci]
