[project]
name = "bus-sign"
revision = "1.0"

[providers]
local = "dotenv://.env"
vault = "vault://secrets.scottylabs.org/secret"

[profiles.ci.defaults]
required = false

[profiles.default]
PRT_API_KEY = { description = "Pittsburgh Regional Transit API key" }
OPENWEATHER_API_KEY = { description = "OpenWeatherMap API key" }

[profiles.prod]

[profiles.preview]

[profiles.staging]

[profiles.dev]
PRT_API_KEY = { providers = ["local"] }
OPENWEATHER_API_KEY = { providers = ["local"] }
