name: Backend CI
on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: docker
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4

      - uses: https://github.com/dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Check
        run: cargo check --manifest-path backend/Cargo.toml

      - name: Test
        run: cargo test --manifest-path backend/Cargo.toml

      - name: Format
        run: cargo fmt --manifest-path backend/Cargo.toml --all -- --check

      - name: Clippy
        run: cargo clippy --manifest-path backend/Cargo.toml -- -D warnings
