name: Frontend CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: docker
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4

      - uses: https://github.com/oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Check
        run: bun run check
